/*
    FILE: particles.h
    Defines the Particle class, an object with position, velocity, etc. that
    isn't processed as a separate entity and instead attached to a ParticleGenerator
    component.
*/
#include<raylib.h>
#include"utility.h"

// Defines the particles generated by the ParticleGenerator component. Texture isn't stored
// because the texture is part of the ParticleGenerator itself.
class Particle {
  private:
    Color m_color;
    Vector2 m_relativePos;
    Vector2 m_velocity;
    Vector2 m_acceleration;
    float m_currentAngle; // in degrees!
    float m_rotationalVelocity;
    float m_timeToLive;
    Particle();
  public:
    // Constructs a particle with the following initial values.
    Particle(
        const Color& color,
        const Vector2& relativePos,
        const Vector2& velocity,
        const Vector2& acceleration,
        float angle,
        float rotationalVelocity,
        float lifetime
    );

    // Copy and move constructors and assignment operators
    ;
    Particle(const Particle&) = default;
    Particle(Particle&&) = default;
    Particle& operator=(const Particle& other) = default;
    Particle& operator=(Particle&& other) = default;
    // Updates the particle's position, velocity, based on the given frame time.
    void update(float delta);
    // Returns true when the particle's lifetime clock has reached zero, as an indicator
    // that the owning ParticleGenerator should remove it from the pool
    bool shouldDie() const;
    // Draws the individual particle with a given texture and global position (the particle's)
    // position is only relative.
    // TODO: this ideally should only be done in one draw call. how? idk
    void draw(const Texture& texture, const Vector2& position) const;
};
